






[*]

jinja=true


c = 35000
; b = 4096
; ub = 1024

; ; n = 512
; t = 12 # cpu thread count
; ; ngl = 999 # num layers to offload to gpu
; ; n-cpu-moe = 13 # how many moe layers to run on cpu

; # kv quant
; ctk = q8_0
; ctv = q8_0

; no-mmap = true

; fa = true

; # fit options
; fit = true
; fit-ctx = 96000
; ; fit-target = 256

; # sampling
; temp = 0.6
; top-p = 0.95
; top-k = 20
; min-p = 0.0
; presence-penalty = 0.0
; repeat-penalty = 1.0

; # reasoning
; reasoning-budget = -1

; # JSON stays unescaped in ini
; chat-template-kwargs = {"preserve_thinking": true}
