keys:
  # - &jdy-laptop age1z4mhn00ag8nem494uhzyl298g0mwlr70p69950793r4z36m50vkqqumvnk
  # - &mv-church age1zs95dfln3uy5tkm3kz8s7gczm6drfdpcsa3f72h3drkuq5aduqyskdpdje
  - &oracle-main age12cfar29uckq8pg20h4r9hkf90ya0s3q2c5uwwh5ykxsnpxdkydjs7qqczs
  - &jdy-desktop age1rqpwp3fvmcjpygdvx2uuhve5zrtjekcf2l7whuvv5h7jdz2k0q5q97cavy
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      # - *jdy-laptop
      # - *jdy-desktop
      - *oracle-main
      - *jdy-desktop


# ======================================================================
#  SOPS Management
# ======================================================================

# ========= Add New Keys =========
# Generate new SSH key:
#   `ssh-keygen -t ed25519`
#
# View SSH age public key:
#   `nix-shell -p ssh-to-age --run 'ssh-to-age < ~/.ssh/id_ed25519.pub'`
#
# View remote SSH key age public key:
#   `nix-shell -p ssh-to-age --run "ssh-keyscan <remote> | ssh-to-age"`
#
# Add age key in list above
#
# Update secrets file with new keys:
#   `nix-shell -p sops --run 'sops updatekeys secrets.yaml'`
# 
#
#
# ========= Edit Secrets =========
# Edit encrypted secrets file:
#   nix-shell -p sops --run 'sops secrets.yaml'
# 

# ========= Access Secrets =========
# secret file - config.sops.secrets."<name>".path;
# secret string - config.sops.placeholder."<name>";


