keys:
  - &jdy-laptop age1z4mhn00ag8nem494uhzyl298g0mwlr70p69950793r4z36m50vkqqumvnk
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *jdy-laptop

# generate private key - nix-shell -p ssh-to-age --run "ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt"
# get public key - nix-shell -p ssh-to-age --run "ssh-to-age < ~/.ssh/id_ed25519.pub"
# get public key from remote computer - nix-shell -p ssh-to-age --run 'ssh-keyscan example.com | ssh-to-age'
# edit secrets.yaml - nix-shell -p sops --run "sops secrets.yaml"
